In [2]:
from pycaret.classification import *
import pandas as pd

In [36]:

dataset = pd.read_csv('../../Data/testData_2019_2021.csv')
dataset.drop([ 'change in next day (%)'], axis=1, inplace=True)
dataset

,Date,Open,High,Low,Close,Volume,change (%),NewsCount,Sentiment,nextDay_prediction
0,2019/01/01,3746.713379,3850.913818,3707.231201,3843.520020,4.324201e+09,2.584,11,-1,POSITIVE
1,2019/01/02,3849.216309,3947.981201,3817.409424,3943.409424,5.244857e+09,2.447,35,0,NEGATIVE
2,2019/01/03,3931.048584,3935.685059,3826.222900,3836.741211,4.530215e+09,-2.399,51,13,POSITIVE
3,2019/01/04,3832.040039,3865.934570,3783.853760,3857.717529,4.847965e+09,0.670,29,3,NEGATIVE
4,2019/01/05,3851.973877,3904.903076,3836.900146,3845.194580,5.137610e+09,-0.176,17,4,POSITIVE
...,...,...,...,...,...,...,...,...,...,...
1091,2021/12/27,50802.609380,51956.328130,50499.468750,50640.417970,2.432435e+10,-0.319,139,35,NEGATIVE
1092,2021/12/28,50679.859380,50679.859380,47414.210940,47588.855470,3.343038e+10,-6.099,170,36,NEGATIVE
1093,2021/12/29,47623.871090,48119.742190,46201.496090,46444.710940,3.004923e+10,-2.476,163,31,POSITIVE
1094,2021/12/30,46490.605470,47879.964840,46060.312500,47178.125000,2.668649e+10,1.479,134,22,NEGATIVE
1095,2021/12/31,47169.371090,48472.527340,45819.953130,46306.445310,3.697417e+10,-1.829,149,44,POSITIVE

In [58]:
exp = setup(dataset, target = 'nextDay_prediction', 
            fold = 15,
            data_split_shuffle= False,
            train_size=0.8,
            # normalize = True, 
            # transformation = True, 
            ignore_low_variance = True,
            remove_multicollinearity = True,
            multicollinearity_threshold = 0.98,
            # log_experiment = True, experiment_name = 'credit1',
            # # bin_numeric_features = ['Date']
)

In [59]:
top3 = compare_models(n_select = 3)

In [60]:
dt = create_model('nb')
lr= create_model('lr')

In [62]:
tuned_dt = tune_model(dt, n_iter=200)

In [63]:
tuned_lr = tune_model(lr, n_iter=200)

In [64]:
predict_model(tuned_dt)

,High,Volume,change (%),NewsCount,Sentiment,Date_month_1,Date_month_10,Date_month_11,Date_month_12,Date_month_2,...,Date_weekday_2,Date_weekday_3,Date_weekday_4,Date_weekday_5,Date_weekday_6,Date_is_month_end_1,Date_is_month_start_1,nextDay_prediction,Label,Score
0,40782.078125,5.134674e+10,2.348,42.0,6.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NEGATIVE,POSITIVE,0.5320
1,40379.617188,4.321097e+10,-2.238,31.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NEGATIVE,POSITIVE,0.5804
2,38856.968750,5.520019e+10,-7.296,38.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NEGATIVE,POSITIVE,0.5016
3,37234.500000,4.523101e+10,-2.993,24.0,-4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,POSITIVE,POSITIVE,0.5704
4,36400.667969,3.164608e+10,3.094,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,POSITIVE,POSITIVE,0.6133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,51956.328125,2.432435e+10,-0.319,139.0,35.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NEGATIVE,POSITIVE,0.6134
216,50679.859375,3.343038e+10,-6.099,170.0,36.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NEGATIVE,POSITIVE,0.6109
217,48119.742188,3.004923e+10,-2.476,163.0,31.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,POSITIVE,POSITIVE,0.6147
218,47879.964844,2.668649e+10,1.479,134.0,22.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NEGATIVE,POSITIVE,0.6151
219,48472.527344,3.697417e+10,-1.829,149.0,44.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,POSITIVE,POSITIVE,0.6032

In [68]:
evaluate_model(tuned_lr)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [34]:
a = create_model(best_model)
cf_withNews = tune_model(a, n_iter=50)

In [35]:
predict_model(cf_withNews)

,Low,Volume,news,SENTIMENTAL_POSITIVE,Date_month_1,Date_month_10,Date_month_11,Date_month_12,Date_month_2,Date_month_3,...,Date_weekday_2,Date_weekday_3,Date_weekday_4,Date_weekday_5,Date_weekday_6,Date_is_month_end_0,Date_is_month_start_1,next day prediction,Label,Score
0,3961.657471,9.856167e+09,14.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0,0,0.2294
1,10622.921875,5.374597e+10,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0,1,0.3101
2,5193.382324,1.550459e+10,33.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1,1,0.3072
3,3442.586914,5.332719e+09,57.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0.2348
4,9058.664062,1.788926e+10,44.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1,0,0.2736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,9784.563477,3.938655e+10,38.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1,0.3241
143,5250.506836,1.325649e+10,44.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0,1,0.3687
144,10632.631836,2.876655e+10,57.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1,0.2643
145,5708.035156,1.480883e+10,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0,1,0.2809
146,6924.375977,1.688113e+10,19.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,-1,1,0.3069

In [36]:
evaluate_model(cf_withNews)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦